### ISSUE TITLE
Generators don't consume fuel or do anything at all.

### ISSUE THREAD

**Issue by Jacob345k** [kjmaster1/InventoryGenerators#10]
Tried changing charging mode, putting it all around my inventory, etc, just wont work.
![javaw_2018-08-26_20-14-24](https://user-images.githubusercontent.com/25356889/44635643-a1bed380-a96c-11e8-8fde-ad914d379c3d.png)
![image](https://user-images.githubusercontent.com/25356889/44635648-a6838780-a96c-11e8-9e6e-f74a01c1fab8.png)
![image](https://user-images.githubusercontent.com/25356889/44635655-b307e000-a96c-11e8-93f5-a232d6e6a66a.png)

**Comment by kjmaster1** [comment]
Have you right clicked the generator to open the GUI and insert fuel? I added GUIs to the generators in the 1.1.0 update.
