### ISSUE TITLE
1.14.4 All the mods world crash and corrupt

### ISSUE THREAD

**Issue by lothar92** [kjmaster1/InventoryGenerators#13]
was playing around with inventory generators (never used it before) and accidently shift clicked one generator into another. game instantly crashed and now crashes on launch. is there a way to disable shift clicking into the generator inventories? 

Minecraft Version: 1.14.4

(modded) forge-28.1.104

Can attach crash report if you'd like, should be pretty easy to replicate though =)

[edit - tried deleting player data folder to see if that would fix, game now freezes at 100% loading world and generates no crash report]

**Comment by alex-van-vliet** [comment]
I did not shift click one generator into another generator, but I am having the same issue with all the mods 4
For an unknown reason the game crashed and now it also crashes on launch

I can also attach my crash report if needed

**Comment by kjmaster1** [comment]
Yeah both crash reports would be appreciated, thanks.

**Comment by vortexcube** [comment]
I shift-clicked an upgrade into the generator. It went into the generator slot. Crash. Couldn't load up the savegame afterwards. I had to remove the mod.

https://gist.github.com/vortexcube/66d3f0a0406795f7a2a653040fa34a00

**Comment by kjmaster1** [comment]
Being able to shift click invalid items into the generator slot should be fixed in 1.15.1-1.0.1
