### ISSUE TITLE
Crash when launching

### ISSUE THREAD

**Issue by Fatemaster01** [kjmaster1/InventoryGenerators#9]
All The Mods 3 will not load, I have allocated the correct amount of memory, I have not changed any files, my Java is up to date.  After seeking help from the All The Mods 3 staff, and producing an error log (linked here), it seems that the issue is from "InventoryGenerators" and I was directed to post my issue here. 
https://pastebin.com/iKR3cu9C

**Comment by Kittypire** [comment]
Fatemaster01 has updated InventoryGenerators since this post and it is still crashing. :(
